package store

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"
)

var (
	ErrGlobalUserNotFound = errors.New("global user not found")
	ErrInvalidLeaseInput  = errors.New("invalid activity lease input")
)

// ActivityLease is the durable single-writer lease for one global user.
type ActivityLease struct {
	UserID               int64
	WriterNodeID         int64
	SessionID            string
	ActivityEpoch        int64
	State                string
	LeaseExpiresAt       time.Time
	LastPageHeartbeatAt  time.Time
	LastRequestAt        time.Time
	InFlightReads        int
	InFlightWrites       int
	ControllerGeneration int64
	UpdatedAt            time.Time
}

// AcquireActivityLeaseParams describes one idempotent attempt to establish a
// new writer. OperationID and SessionID are UUID strings generated by the
// controller. An unexpired lease is never replaced, even when the caller asks
// for the same node; the caller must route the user back to the existing lease.
type AcquireActivityLeaseParams struct {
	OperationID          string
	UserID               int64
	WriterNodeID         int64
	SessionID            string
	ControllerGeneration int64
	TTL                  time.Duration
	Now                  time.Time
}

// AcquireActivityLeaseResult distinguishes a newly acquired writer from an
// existing writer that the login flow must preserve.
type AcquireActivityLeaseResult struct {
	Lease    ActivityLease
	Acquired bool
	Existing bool
}

// AcquireActivityLease atomically establishes the only active writer for a
// global user. It locks the global user row so simultaneous first acquisitions
// cannot both observe an absent lease, and records the result under a stable
// operation ID for safe retries.
func (s *Store) AcquireActivityLease(ctx context.Context, p AcquireActivityLeaseParams) (AcquireActivityLeaseResult, error) {
	if err := validateActivityLeaseParams(p); err != nil {
		return AcquireActivityLeaseResult{}, ErrInvalidLeaseInput
	}
	if p.Now.IsZero() {
		p.Now = time.Now().UTC()
	}

	tx, err := s.DB.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return AcquireActivityLeaseResult{}, err
	}
	defer func() { _ = tx.Rollback() }()

	if err := lockGlobalUser(ctx, tx, p.UserID); err != nil {
		return AcquireActivityLeaseResult{}, err
	}
	result, _, err := acquireActivityLeaseLocked(ctx, tx, p)
	if err != nil {
		return AcquireActivityLeaseResult{}, err
	}
	if err := tx.Commit(); err != nil {
		return AcquireActivityLeaseResult{}, err
	}
	return result, nil
}

func validateActivityLeaseParams(p AcquireActivityLeaseParams) error {
	if p.OperationID == "" || p.SessionID == "" || p.UserID <= 0 || p.WriterNodeID <= 0 ||
		p.ControllerGeneration <= 0 || p.TTL <= 0 {
		return ErrInvalidLeaseInput
	}
	return nil
}

func lockGlobalUser(ctx context.Context, tx *sql.Tx, userID int64) error {
	var lockedID int64
	if err := tx.QueryRowContext(ctx,
		`SELECT id FROM global_users WHERE id=$1 FOR UPDATE`, userID).Scan(&lockedID); err != nil {
		if err == sql.ErrNoRows {
			return ErrGlobalUserNotFound
		}
		return fmt.Errorf("lock global user: %w", err)
	}
	return nil
}

// acquireActivityLeaseLocked applies the lease transition inside a caller-owned
// serializable transaction. The global user row must already be locked.
func acquireActivityLeaseLocked(
	ctx context.Context,
	tx *sql.Tx,
	p AcquireActivityLeaseParams,
) (AcquireActivityLeaseResult, bool, error) {
	if result, ok, err := getLeaseOperation(ctx, tx, p.OperationID); err != nil {
		return AcquireActivityLeaseResult{}, false, err
	} else if ok {
		return result, true, nil
	}

	lease, found, err := getActivityLeaseForUpdate(ctx, tx, p.UserID)
	if err != nil {
		return AcquireActivityLeaseResult{}, false, err
	}
	if found && leaseBlocksNewWriter(lease, p.Now) {
		result := AcquireActivityLeaseResult{Lease: lease, Existing: true}
		if err := recordLeaseOperation(ctx, tx, p, "existing", lease); err != nil {
			return AcquireActivityLeaseResult{}, false, err
		}
		return result, false, nil
	}

	nextEpoch := int64(1)
	if found {
		nextEpoch = lease.ActivityEpoch + 1
	}
	lease = ActivityLease{
		UserID:               p.UserID,
		WriterNodeID:         p.WriterNodeID,
		SessionID:            p.SessionID,
		ActivityEpoch:        nextEpoch,
		State:                "active",
		LeaseExpiresAt:       p.Now.Add(p.TTL),
		LastPageHeartbeatAt:  p.Now,
		LastRequestAt:        p.Now,
		ControllerGeneration: p.ControllerGeneration,
		UpdatedAt:            p.Now,
	}
	if _, err := tx.ExecContext(ctx, `
		INSERT INTO user_activity_leases (
		  user_id, writer_node_id, session_id, activity_epoch, state,
		  lease_expires_at, last_page_heartbeat_at, last_request_at,
		  in_flight_reads, in_flight_writes, controller_generation, updated_at
		) VALUES ($1,$2,$3,$4,'active',$5,$6,$6,0,0,$7,$6)
		ON CONFLICT (user_id) DO UPDATE SET
		  writer_node_id=EXCLUDED.writer_node_id,
		  session_id=EXCLUDED.session_id,
		  activity_epoch=EXCLUDED.activity_epoch,
		  state='active',
		  lease_expires_at=EXCLUDED.lease_expires_at,
		  last_page_heartbeat_at=EXCLUDED.last_page_heartbeat_at,
		  last_request_at=EXCLUDED.last_request_at,
		  in_flight_reads=0,
		  in_flight_writes=0,
		  controller_generation=EXCLUDED.controller_generation,
		  updated_at=EXCLUDED.updated_at`,
		p.UserID, p.WriterNodeID, p.SessionID, nextEpoch, lease.LeaseExpiresAt, p.Now,
		p.ControllerGeneration); err != nil {
		return AcquireActivityLeaseResult{}, false, fmt.Errorf("upsert activity lease: %w", err)
	}
	if err := recordLeaseOperation(ctx, tx, p, "acquired", lease); err != nil {
		return AcquireActivityLeaseResult{}, false, err
	}
	return AcquireActivityLeaseResult{Lease: lease, Acquired: true}, false, nil
}

// RenewActivityLease extends exactly the currently fenced session and epoch.
// A stale browser cannot renew a newer lease because every identity component
// participates in the conditional update.
func (s *Store) RenewActivityLease(
	ctx context.Context,
	userID, writerNodeID int64,
	sessionID string,
	activityEpoch, controllerGeneration int64,
	now time.Time,
	ttl time.Duration,
) (bool, error) {
	if userID <= 0 || writerNodeID <= 0 || sessionID == "" || activityEpoch <= 0 ||
		controllerGeneration <= 0 || ttl <= 0 {
		return false, ErrInvalidLeaseInput
	}
	if now.IsZero() {
		now = time.Now().UTC()
	}
	result, err := s.DB.ExecContext(ctx, `
		UPDATE user_activity_leases
		SET lease_expires_at=$7, last_page_heartbeat_at=$6, updated_at=$6
		WHERE user_id=$1 AND writer_node_id=$2 AND session_id=$3
		  AND activity_epoch=$4 AND controller_generation=$5 AND state='active'`,
		userID, writerNodeID, sessionID, activityEpoch, controllerGeneration, now, now.Add(ttl))
	if err != nil {
		return false, err
	}
	rows, err := result.RowsAffected()
	return rows == 1, err
}

// EndActivityLease fences the exact current session. It is idempotent: ending
// an already ended or superseded lease returns false without changing it.
func (s *Store) EndActivityLease(
	ctx context.Context,
	userID, writerNodeID int64,
	sessionID string,
	activityEpoch, controllerGeneration int64,
	now time.Time,
) (bool, error) {
	if userID <= 0 || writerNodeID <= 0 || sessionID == "" || activityEpoch <= 0 || controllerGeneration <= 0 {
		return false, ErrInvalidLeaseInput
	}
	if now.IsZero() {
		now = time.Now().UTC()
	}
	result, err := s.DB.ExecContext(ctx, `
		UPDATE user_activity_leases
		SET state='ended', lease_expires_at=$6, updated_at=$6
		WHERE user_id=$1 AND writer_node_id=$2 AND session_id=$3
		  AND activity_epoch=$4 AND controller_generation=$5
		  AND state IN ('active','quiescing','drained','independent')`,
		userID, writerNodeID, sessionID, activityEpoch, controllerGeneration, now)
	if err != nil {
		return false, err
	}
	rows, err := result.RowsAffected()
	return rows == 1, err
}

func leaseBlocksNewWriter(lease ActivityLease, now time.Time) bool {
	switch lease.State {
	case "active", "quiescing", "drained", "independent":
		return lease.LeaseExpiresAt.After(now)
	default:
		return false
	}
}

func getActivityLeaseForUpdate(ctx context.Context, tx *sql.Tx, userID int64) (ActivityLease, bool, error) {
	var lease ActivityLease
	err := tx.QueryRowContext(ctx, `
		SELECT user_id, writer_node_id, session_id, activity_epoch, state,
		  lease_expires_at, last_page_heartbeat_at, last_request_at,
		  in_flight_reads, in_flight_writes, controller_generation, updated_at
		FROM user_activity_leases WHERE user_id=$1 FOR UPDATE`, userID).
		Scan(&lease.UserID, &lease.WriterNodeID, &lease.SessionID, &lease.ActivityEpoch, &lease.State,
			&lease.LeaseExpiresAt, &lease.LastPageHeartbeatAt, &lease.LastRequestAt,
			&lease.InFlightReads, &lease.InFlightWrites, &lease.ControllerGeneration, &lease.UpdatedAt)
	if err == sql.ErrNoRows {
		return ActivityLease{}, false, nil
	}
	if err != nil {
		return ActivityLease{}, false, fmt.Errorf("get activity lease: %w", err)
	}
	return lease, true, nil
}

func getLeaseOperation(ctx context.Context, tx *sql.Tx, operationID string) (AcquireActivityLeaseResult, bool, error) {
	var (
		outcome   string
		nodeID    sql.NullInt64
		sessionID sql.NullString
		epoch     sql.NullInt64
	)
	err := tx.QueryRowContext(ctx, `
		SELECT outcome, result_writer_node_id, result_session_id, result_activity_epoch
		FROM activity_lease_operations WHERE operation_id=$1`, operationID).
		Scan(&outcome, &nodeID, &sessionID, &epoch)
	if err == sql.ErrNoRows {
		return AcquireActivityLeaseResult{}, false, nil
	}
	if err != nil {
		return AcquireActivityLeaseResult{}, false, fmt.Errorf("get lease operation: %w", err)
	}
	result := AcquireActivityLeaseResult{
		Lease: ActivityLease{
			WriterNodeID:  nodeID.Int64,
			SessionID:     sessionID.String,
			ActivityEpoch: epoch.Int64,
		},
		Acquired: outcome == "acquired",
		Existing: outcome == "existing",
	}
	return result, true, nil
}

func recordLeaseOperation(
	ctx context.Context,
	tx *sql.Tx,
	p AcquireActivityLeaseParams,
	outcome string,
	lease ActivityLease,
) error {
	if _, err := tx.ExecContext(ctx, `
		INSERT INTO activity_lease_operations (
		  operation_id, user_id, requested_node_id, requested_session_id, outcome,
		  result_writer_node_id, result_session_id, result_activity_epoch, created_at
		) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,
		p.OperationID, p.UserID, p.WriterNodeID, p.SessionID, outcome,
		lease.WriterNodeID, lease.SessionID, lease.ActivityEpoch, p.Now); err != nil {
		return fmt.Errorf("record lease operation: %w", err)
	}
	return nil
}
